version: '2'
services:
  nginx:
    image: nginx:alpine
    hostname: nginx
    container_name: nginx
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /opt/ssl/nginx/nginx.conf:/etc/nginx/nginx.conf
    - /opt/ssl:/etc/nginx/ssl
    depends_on:
      - jekyll

  jekyll:
    image: jicki/jekyll
    hostname: jekyll
    container_name: jekyll
    restart: always 
